Update avatar models to use MToonMaterial
webaverse/metaversefile pull request #34
Opened 2021-11-24 09:17 UTC by yaserOSource

This PR enables use of MToonMaterial. 

Please look at the first 2 images for comparison. 

The last image is an art reference.

![image](https://user-images.githubusercontent.com/51108458/143209250-24a2d73e-4e26-4240-8be8-326a805019a1.png)
![image](https://user-images.githubusercontent.com/51108458/143209264-e34d5d6c-4479-4b38-9297-0d0e97aa092d.png)
![image](https://user-images.githubusercontent.com/51108458/143209486-710ba112-a857-48ef-b292-7cd232a62850.png)

QA Checklist:

Look at the avatar face in the mirror, and up close with the camera, you should see some 'toon' shading.
Look at the avatar hair and body, you should see movement in the hair and other parts that might contain a 'springy' animation.

2021-11-24 09:23 UTC, avaer commented
Can the art reference card be an app or something? Looks really useful.

2021-11-24 09:38 UTC, yaserOSource commented
https://github.com/yaserOSource/avatar-test right here if you want to test them or upload them to app/public/avatars

2021-11-24 09:39 UTC, yaserOSource commented
We can make it an app...too

2021-11-24 10:49 UTC, avaer commented
What does https://github.com/yaserOSource/avatar-test have to do with the "art refrence" card?

![](https://user-images.githubusercontent.com/51108458/143209486-710ba112-a857-48ef-b292-7cd232a62850.png)

2021-11-24 11:25 UTC, yaserOSource commented
The reference spheres are amongst those models.

vian.glb
vian.vrm

2021-11-24 11:33 UTC, yaserOSource commented
https://github.com/yaserOSource/material-debug-assets 

its these 2 assets, they were amongst the other avatars in that previously posted repo.

2021-11-24 12:44 UTC, avaer commented
Got it, thanks for clarifying the naming.

2021-11-24 14:20 UTC, Vianvolaeus commented
They're standalone models, so they can be tested easily across diff. engines for comparisons. The MToon one is equippable as a VRM avatar.

2021-11-24 20:25 UTC, skaljac commented
It works for me
![Screenshot (8)](https://user-images.githubusercontent.com/4487857/143308458-06034301-7ed8-4101-bb91-36aee3dba41f.png)
![Screenshot (9)](https://user-images.githubusercontent.com/4487857/143308468-d2cd0f5f-6f16-42e6-93f3-9430621492e3.png)
.

2021-11-25 00:30 UTC, amnaarshed4224 commented
This PR works fine with avatar's faces.

2021-11-25 02:08 UTC, avaer commented on type_templates/vrm.js
> +  const materials = await vrmImporter.convertGLTFMaterials(o);
As far as I can tell `convertGLTFMaterials` will already attach the converted materials.

https://github.com/pixiv/three-vrm/blob/96debe1ca3b3db8a462db0386af048f0d8339e87/packages/three-vrm/src/material/VRMMaterialImporter.ts#L99

So is the below loop even needed?

2021-11-25 02:08 UTC, avaer requested changes
One question, the rest looks like a great solution!

2021-11-25 04:45 UTC, yaserOSource commented
This has been updated and the extra loop removed.

So its ready for merge.

2021-11-26 05:08 UTC, merged

2021-12-03 15:05 UTC, avaer commented
This was not sufficiently tested and caused a crash when switching scenes.

In addition, I found race condition problems in this PR, where we do not wait for the shader to switch even though it is asynchronous.

2021-12-03 15:05 UTC, avaer commented
![image](https://user-images.githubusercontent.com/6926057/144624861-862f713f-71a5-400f-9d0c-aa0f51a434d0.png)

2021-12-03 15:10 UTC, avaer commented
This PR was reverted in https://github.com/webaverse/totum/commit/527994408e9d669e07943f32d01d495f79fd6a35